# Config for single device full finetuning in full_finetune_single_device.py
# using a Llama3.1 8B Instruct model
#
# This config assumes that you've run the following command before launching
# this run:
#   tune download meta-llama/Meta-Llama-3.1-8B-Instruct --output-dir /tmp/Meta-Llama-3.1-8B-Instruct --ignore-patterns "original/consolidated.00.pth"
#
# The default config uses an optimizer from bitsandbytes. If you do not have it installed,
# you can install it with
#   pip install bitsandbytes
#
# To launch on a single device, run the following command from root:
#   tune run full_finetune_single_device --config llama3_1/8B_full_single_device
#
# You can add specific overrides through the command line. For example
# to override the checkpointer directory while launching training
# you can run:
#   tune run full_finetune_single_device --config llama3_1/8B_full_single_device checkpointer.checkpoint_dir=<YOUR_CHECKPOINT_DIR>
#
# This config works only for training on single device.


output_dir: /tmp/torchtune/llama3_1_8B/full_single_device # /tmp may be deleted by your system. Change it to your preference.

# Tokenizer
tokenizer:
  _component_: torchtune.models.llama3.llama3_tokenizer
  path: /fs/nexus-scratch/vatsalb/Meta-Llama-3.1-8B-Instruct/original/tokenizer.model
  prompt_template:
    system:
      - "System: "
      - "\\n"
    user:
      - "Evaluate policy compliance for this conversation: "
      - "\\n"
    assistant:
      - "Compliance Evaluation: "
      - "\\n"
  max_seq_len: null

# Dataset
dataset:
  _component_: torchtune.datasets.instruct_dataset
  source: json
  data_files: data/compliance_dataset.json
  split: train
  new_system_prompt: "You are a guardian model evaluating the compliance of a chatbot agent to system prompt policies.\
   You will be given a system prompt for the agent, a numbered list of policies that the agent needs to follow, and a conversation between the agent and a user.\
   The policies will be listed in the following format:\n1. [policy 1]\n2. [policy 2]\nand so on.\
   The conversation will be in the following format:\n'User': [user query]\n'Chatbot': [chatbot response]\
   Your task is to evaluate the conversation in the context of the policies, and determine which of the policies (if any) have been violated.
   Respond with a compliance evaluation starting with 'Compliance Evaluation':, followed by a numbered list corresponding to the policies, with the value for each policy being PASS or FAIL.\
   Output PASS for a policy if the conversation between the agent and the user was compliant with the policy.\
   Output FAIL for a policy if the agent at any time responded in a manner that violated the policy.
   In the case of outputting FAIL, you must also provide a brief explanation of how the chatbot violated the policy. Cite specific examples of how the policy was violated.\
   Your output must adhere to this following format:\n1. [PASS or FAIL]\n2. [PASS or FAIL]\n and so on, for each policy."
seed: null
shuffle: True

# Model Arguments
model:
  _component_: torchtune.models.llama3_1.llama3_1_8b

checkpointer:
  _component_: torchtune.training.FullModelHFCheckpointer
  checkpoint_dir: /fs/nexus-scratch/vatsalb/Meta-Llama-3.1-8B-Instruct/
  checkpoint_files: [
    model-00001-of-00004.safetensors,
    model-00002-of-00004.safetensors,
    model-00003-of-00004.safetensors,
    model-00004-of-00004.safetensors
  ]
  recipe_checkpoint: null
  output_dir: /fs/nexus-scratch/vatsalb/Meta-Llama-3.1-8B-Instruct/
  model_type: LLAMA3
resume_from_checkpoint: False

# Fine-tuning arguments
batch_size: 2
epochs: 1
optimizer:
  _component_: bitsandbytes.optim.PagedAdamW8bit
  lr: 2e-5
loss:
  _component_: torchtune.modules.loss.LinearCrossEntropyLoss
max_steps_per_epoch: null
gradient_accumulation_steps: 1  # Use to increase effective batch size
optimizer_in_bwd: True  # True saves memory. Requires gradient_accumulation_steps=1
clip_grad_norm: null
compile: False  # torch.compile the model + loss, True increases speed + decreases memory

# Training environment
device: cuda

# Memory management
enable_activation_checkpointing: True  # True reduces memory
enable_activation_offloading: False  # True reduces memory

# Reduced precision
dtype: bf16

# Logging
metric_logger:
  _component_: torchtune.training.metric_logging.DiskLogger
  log_dir: ${output_dir}
output_dir: /fs/nexus-scratch/vatsalb/full-llama3.1-finetune
log_every_n_steps: 1
log_peak_memory_stats: True
log_level: INFO  # DEBUG, WARN, etc.


# Profiler (disabled)
profiler:
  _component_: torchtune.training.setup_torch_profiler
  enabled: False

  #Output directory of trace artifacts
  output_dir: ${output_dir}/profiling_outputs

  #`torch.profiler.ProfilerActivity` types to trace
  cpu: True
  cuda: True

  #trace options passed to `torch.profiler.profile`
  profile_memory: False
  with_stack: False
  record_shapes: True
  with_flops: False

  # `torch.profiler.schedule` options:
  # wait_steps -> wait, warmup_steps -> warmup, active_steps -> active, num_cycles -> repeat
  wait_steps: 5
  warmup_steps: 3
  active_steps: 2
  num_cycles: 1
